# Generated by Django 3.2 on 2023-06-16 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Humedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dato', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='fecha de registro')),
            ],
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('humedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.humedad')),
            ],
        ),
    ]
