# Generated by Django 3.2 on 2023-06-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='humedad',
            name='nombre',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
