# Generated by Django 3.2 on 2023-06-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_humedad_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha de publicacion'),
        ),
    ]
