# Generated by Django 3.2 on 2023-06-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_alter_humedad_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humedad',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
