# Generated by Django 3.2 on 2023-06-20 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0006_temperatura_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='temperatura',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='sistema.temperatura'),
            preserve_default=False,
        ),
    ]
