# Generated by Django 3.2 on 2023-06-29 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0007_planta_temperatura'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='contraseña',
            new_name='clave',
        ),
        migrations.RemoveField(
            model_name='humedad',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='planta',
            name='humedad',
        ),
        migrations.RemoveField(
            model_name='planta',
            name='temperatura',
        ),
        migrations.AddField(
            model_name='planta',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='planta',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='planta/'),
        ),
        migrations.DeleteModel(
            name='Temperatura',
        ),
    ]
